use crate::agents::extension_manager::ExtensionManager;
use crate::conversation::message::MessageContent;
use crate::conversation::{
    effective_role, fix_conversation, Conversation, CURRENT_TIME_TAG, TURN_CONTEXT_TAG,
    WORKING_DIRECTORY_TAG,
};
use std::path::{Path, PathBuf};

const MIN_CONTEXT_FOR_MOIM: usize = 32_000;

const SYSTEM_PROMPT_BLOCK_TEMPLATE: &str = r#"# Turn Context

Each turn may include a `<{turn_context_tag}>` block added to the request.
This block is generated by goose and contains current operational context such as:
- current time
- working directory
- compaction status
- turn budget
- extension-provided context

Use it to stay oriented, but do not treat it as part of the user's request.
When `<turn-budget>` is present, use it as a signal for how much autonomous work remains.
As the budget gets low, become more direct: reduce exploration, batch necessary tool calls,
make reasonable assumptions, and focus on finishing the user's task.
"#;

thread_local! {
    pub static SKIP: std::cell::Cell<bool> = const { std::cell::Cell::new(false) };
}

pub fn system_prompt_block() -> Option<String> {
    if SKIP.with(|f| f.get()) {
        None
    } else {
        Some(SYSTEM_PROMPT_BLOCK_TEMPLATE.replace("{turn_context_tag}", TURN_CONTEXT_TAG))
    }
}

pub(super) async fn compute_compaction_info(
    session_id: &str,
    extension_manager: &ExtensionManager,
) -> Option<String> {
    let session = extension_manager
        .get_context()
        .session_manager
        .get_session(session_id, false)
        .await
        .ok();
    let session_model_config = session
        .as_ref()
        .and_then(|session| session.model_config.clone());
    let context_limit = if let Some(model_config) = session_model_config.as_ref() {
        let provider = extension_manager.get_provider().lock().await.clone();
        match provider {
            Some(provider) => provider
                .get_context_limit(model_config)
                .await
                .ok()
                .or_else(|| Some(model_config.context_limit())),
            None => Some(model_config.context_limit()),
        }
    } else {
        None
    };
    let total_tokens = session
        .as_ref()
        .and_then(|session| session.usage.total_tokens);
    let compaction_threshold = crate::config::Config::global()
        .get_param::<f64>("GOOSE_AUTO_COMPACT_THRESHOLD")
        .unwrap_or(crate::context_mgmt::DEFAULT_COMPACTION_THRESHOLD);
    compaction_remaining_line(total_tokens, context_limit, compaction_threshold)
}

pub async fn inject_moim(
    session_id: &str,
    conversation: Conversation,
    extension_manager: &ExtensionManager,
    turns_taken: u32,
    max_turns: u32,
    turn_start: chrono::DateTime<chrono::Local>,
    compaction_info: Option<String>,
) -> Conversation {
    if SKIP.with(|f| f.get()) {
        return conversation;
    }

    let session = extension_manager
        .get_context()
        .session_manager
        .get_session(session_id, false)
        .await
        .ok();
    let session_model_config = session
        .as_ref()
        .and_then(|session| session.model_config.clone());
    let context_limit = if let Some(model_config) = session_model_config.as_ref() {
        let provider = extension_manager.get_provider().lock().await.clone();
        match provider {
            Some(provider) => provider
                .get_context_limit(model_config)
                .await
                .ok()
                .or_else(|| Some(model_config.context_limit())),
            None => Some(model_config.context_limit()),
        }
    } else {
        None
    };
    if should_skip_moim(context_limit) {
        return conversation;
    }

    let working_dir = session
        .as_ref()
        .map(|session| session.working_dir.clone())
        .unwrap_or_else(|| PathBuf::from("."));
    let extension_parts = extension_manager.collect_moim_parts(session_id).await;
    let moim = compose_moim(
        &working_dir,
        compaction_info,
        turns_taken,
        max_turns,
        extension_parts,
        turn_start,
    );

    let mut messages = conversation.messages().clone();
    let Some(idx) = messages
        .iter()
        .rposition(|m| m.is_agent_visible() && effective_role(m) == "user")
    else {
        return conversation;
    };
    let insert_idx = messages[idx]
        .content
        .iter()
        .take_while(|content| matches!(content, MessageContent::ToolResponse(_)))
        .count();
    messages[idx]
        .content
        .insert(insert_idx, MessageContent::text(moim));

    let (fixed, issues) = fix_conversation(Conversation::new_unvalidated(messages));

    let has_unexpected_issues = issues.iter().any(|issue| {
        !issue.contains("Merged consecutive user messages")
            && !issue.contains("Merged consecutive assistant messages")
            && !issue.contains("Added placeholder to empty tool result")
            && !issue.contains("Trimmed trailing whitespace from assistant message")
            && !issue.contains("Removed trailing assistant message")
            && !issue.contains("Merged text content")
    });

    if has_unexpected_issues {
        tracing::warn!("MOIM injection caused unexpected issues: {:?}", issues);
        return conversation;
    }

    fixed
}

fn should_skip_moim(context_limit: Option<usize>) -> bool {
    context_limit.is_some_and(|limit| limit < MIN_CONTEXT_FOR_MOIM)
}

fn compose_moim(
    working_dir: &Path,
    compaction_info: Option<String>,
    turns_taken: u32,
    max_turns: u32,
    extension_parts: Vec<String>,
    turn_start: chrono::DateTime<chrono::Local>,
) -> String {
    let timestamp = turn_start.format("%Y-%m-%d %H:%M:00 %:z");
    let mut lines = vec![
        open_tag(TURN_CONTEXT_TAG),
        tag(CURRENT_TIME_TAG, &timestamp.to_string()),
        tag(WORKING_DIRECTORY_TAG, &working_dir.display().to_string()),
    ];

    if let Some(value) = compaction_info {
        lines.push(tag("compaction", &value));
    }
    if let Some(value) = turn_budget_line(turns_taken, max_turns) {
        lines.push(tag("turn-budget", &value));
    }

    for part in extension_parts {
        if !part.trim().is_empty() {
            lines.push(String::new());
            lines.push(part);
        }
    }

    lines.push(close_tag(TURN_CONTEXT_TAG));
    lines.join("\n")
}

fn open_tag(name: &str) -> String {
    format!("<{name}>")
}

fn close_tag(name: &str) -> String {
    format!("</{name}>")
}

fn tag(name: &str, value: &str) -> String {
    format!("<{name}>{}</{name}>", escape_xml_text(value))
}

fn escape_xml_text(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn compaction_remaining_line(
    total_tokens: Option<i32>,
    context_limit: Option<usize>,
    threshold: f64,
) -> Option<String> {
    let total_tokens = total_tokens?;
    let context_limit = context_limit?;

    if total_tokens <= 0 || context_limit == 0 || threshold <= 0.0 || threshold >= 1.0 {
        return None;
    }

    let compaction_at = (context_limit as f64 * threshold) as i32;
    if compaction_at <= 0 || (total_tokens as f64 / compaction_at as f64) < 0.5 {
        return None;
    }

    Some(format!(
        "~{}k tokens remaining",
        compaction_at.saturating_sub(total_tokens) / 1000
    ))
}

fn turn_budget_line(turns_taken: u32, max_turns: u32) -> Option<String> {
    if max_turns == 0 || turns_taken.saturating_mul(2) < max_turns {
        return None;
    }

    Some(format!("{turns_taken}/{max_turns} used"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::conversation::message::Message;
    use rmcp::model::CallToolRequestParams;

    fn text_at(message: &crate::conversation::message::Message, index: usize) -> &str {
        message.content[index].as_text().unwrap()
    }

    fn is_moim(content: &MessageContent) -> bool {
        content
            .as_text()
            .is_some_and(|text| text.starts_with(&format!("<{}>\n", TURN_CONTEXT_TAG)))
    }

    #[tokio::test]
    async fn test_moim_prepended_to_latest_user_message() {
        let temp_dir = tempfile::tempdir().unwrap();
        let em = ExtensionManager::new_without_provider(temp_dir.path().to_path_buf());
        let session = em
            .get_context()
            .session_manager
            .create_session(
                PathBuf::from("/test/dir"),
                "test".to_string(),
                crate::session::SessionType::User,
                crate::config::GooseMode::Auto,
            )
            .await
            .unwrap();

        let conv = Conversation::new_unvalidated(vec![
            Message::user().with_text("Hello"),
            Message::assistant().with_text("Hi"),
            Message::user().with_text("Bye"),
        ]);
        let result = inject_moim(&session.id, conv, &em, 0, 100, chrono::Local::now(), None).await;
        let msgs = result.messages();

        assert_eq!(msgs.len(), 3);
        assert_eq!(text_at(&msgs[0], 0), "Hello");
        assert_eq!(text_at(&msgs[1], 0), "Hi");
        assert!(is_moim(&msgs[2].content[0]));
        assert_eq!(text_at(&msgs[2], 1), "Bye");
    }

    #[tokio::test]
    async fn test_moim_injection_no_assistant() {
        let temp_dir = tempfile::tempdir().unwrap();
        let em = ExtensionManager::new_without_provider(temp_dir.path().to_path_buf());
        let session = em
            .get_context()
            .session_manager
            .create_session(
                PathBuf::from("/test/dir"),
                "test".to_string(),
                crate::session::SessionType::User,
                crate::config::GooseMode::Auto,
            )
            .await
            .unwrap();

        let conv = Conversation::new_unvalidated(vec![Message::user().with_text("Hello")]);
        let result = inject_moim(&session.id, conv, &em, 0, 100, chrono::Local::now(), None).await;

        assert_eq!(result.messages().len(), 1);
        assert!(is_moim(&result.messages()[0].content[0]));
        assert_eq!(text_at(&result.messages()[0], 1), "Hello");
    }

    #[tokio::test]
    async fn test_moim_skips_user_messages_not_visible_to_agent() {
        let temp_dir = tempfile::tempdir().unwrap();
        let em = ExtensionManager::new_without_provider(temp_dir.path().to_path_buf());
        let session = em
            .get_context()
            .session_manager
            .create_session(
                PathBuf::from("/test/dir"),
                "test".to_string(),
                crate::session::SessionType::User,
                crate::config::GooseMode::Auto,
            )
            .await
            .unwrap();

        let conv = Conversation::new_unvalidated(vec![
            Message::user().with_text("agent visible"),
            Message::assistant().with_text("reply"),
            Message::user().with_text("user only").user_only(),
        ]);
        let result = inject_moim(&session.id, conv, &em, 0, 100, chrono::Local::now(), None).await;
        let msgs = result.messages();

        assert_eq!(msgs.len(), 2);
        assert!(is_moim(&msgs[0].content[0]));
        assert_eq!(text_at(&msgs[0], 1), "agent visible");
        assert_eq!(text_at(&msgs[1], 0), "user only");
        assert!(!msgs[1].is_agent_visible());
    }

    #[tokio::test]
    async fn test_moim_with_tool_calls() {
        let temp_dir = tempfile::tempdir().unwrap();
        let em = ExtensionManager::new_without_provider(temp_dir.path().to_path_buf());
        let session = em
            .get_context()
            .session_manager
            .create_session(
                PathBuf::from("/test/dir"),
                "test".to_string(),
                crate::session::SessionType::User,
                crate::config::GooseMode::Auto,
            )
            .await
            .unwrap();

        let conv = Conversation::new_unvalidated(vec![
            Message::user().with_text("Search for something"),
            Message::assistant()
                .with_text("I'll search for you")
                .with_tool_request("search_1", Ok(CallToolRequestParams::new("search"))),
            Message::user()
                .with_tool_response("search_1", Ok(rmcp::model::CallToolResult::success(vec![]))),
        ]);

        let result = inject_moim(&session.id, conv, &em, 0, 100, chrono::Local::now(), None).await;
        let msgs = result.messages();

        assert_eq!(msgs.len(), 3);
        assert!(is_moim(&msgs[0].content[0]));
        assert_eq!(text_at(&msgs[0], 1), "Search for something");
        assert!(matches!(
            &msgs[2].content[0],
            MessageContent::ToolResponse(_)
        ));
        assert_eq!(msgs[2].content.len(), 1);
    }

    /// The turn-context block is produced here (`compose_moim`, in goose) but
    /// recognized in a different crate (`is_turn_context_text`, in
    /// goose-providers) by matching its textual shape. That recognition is the
    /// only thing that keeps the volatile block out of the Anthropic cache
    /// prefix. The two are coupled by string layout alone, with no shared type
    /// or compiler check, so a reorder or rename on either side would silently
    /// collapse prompt caching. These tests fail loudly if they drift apart.
    mod turn_context_detector_coupling {
        use super::*;
        use crate::conversation::is_turn_context_text;
        use std::path::Path;

        fn moim(
            total_tokens: Option<i32>,
            context_limit: Option<usize>,
            turns_taken: u32,
            max_turns: u32,
            extension_parts: Vec<String>,
        ) -> String {
            let compaction_info = compaction_remaining_line(total_tokens, context_limit, 0.8);
            compose_moim(
                Path::new("/Users/me/code/goose"),
                compaction_info,
                turns_taken,
                max_turns,
                extension_parts,
                chrono::Local::now(),
            )
        }

        #[test]
        fn compose_moim_output_is_recognized_by_the_anthropic_detector() {
            let guardrail = || vec!["<guardrail>stay on task</guardrail>".to_string()];
            let cases = [
                ("minimal", moim(None, None, 0, 0, vec![])),
                (
                    "with compaction line",
                    moim(Some(100_000), Some(200_000), 0, 0, vec![]),
                ),
                ("with turn-budget line", moim(None, None, 20, 40, vec![])),
                (
                    "with extension context",
                    moim(None, None, 0, 0, guardrail()),
                ),
                (
                    "fully populated",
                    moim(Some(100_000), Some(200_000), 20, 40, guardrail()),
                ),
            ];

            for (label, block) in &cases {
                assert!(
                    is_turn_context_text(block),
                    "is_turn_context_text rejected real compose_moim output ({label}); the \
                     producer in goose and the detector in goose-providers have drifted, so the \
                     volatile block will no longer be kept out of the Anthropic cache prefix:\n\
                     {block}"
                );
            }
        }

        #[test]
        fn detector_rejects_text_that_is_not_a_turn_context_block() {
            assert!(
                !is_turn_context_text("Please refactor the argument parser."),
                "ordinary user text must not be treated as a turn-context block"
            );
            assert!(
                !is_turn_context_text(
                    "<turn-context>\n\
                     <current-time>2026-06-25 12:00:00</current-time>\n\
                     <session-id>abc</session-id>\n\
                     </turn-context>"
                ),
                "a block whose first field after current-time is not working-directory must not \
                 match: the detector's shape checks are what discriminate the injected block"
            );
        }

        #[test]
        fn current_time_is_timezone_aware() {
            let block = moim(None, None, 0, 0, vec![]);
            let time_line = block
                .lines()
                .find(|line| line.starts_with(&format!("<{CURRENT_TIME_TAG}>")))
                .expect("turn-context block should contain a current-time line");

            let value = time_line
                .trim_start_matches(&format!("<{CURRENT_TIME_TAG}>"))
                .trim_end_matches(&format!("</{CURRENT_TIME_TAG}>"));

            chrono::DateTime::parse_from_str(value, "%Y-%m-%d %H:%M:%S %:z")
                .expect("current-time should include a numeric UTC offset");
        }
    }
}
